### ISSUE TITLE
[question][chapter08] 언제 json형태로 데이터 저장을 하는게 유용할까요?

### ISSUE THREAD

**Issue by JisuPark-dev** [RealMysql-2407/study#10]
이번장에서 멀티벨류 인덱스에 대한 이야기가 있었습니다.
멀티벨류 = json이라고 생각이 되는데요.

그럼 RDBMS에서 언제 json형태로 데이터를 저장하는 것이 좋을까요?
json형태로 저장할 수 있는 데이터라면 오히려 테이블을 파는 것이 관계형 데이터베이스의 취지에 더 맞는 것이 아닐까요?

예를 들어서 환자 테이블에 개인정보 이용 약관 칼럼이 있다고 생각해봅시다. 약관동의는 필수와 선택으로 구분됩니다.
해당 환자가 동의한 약관 항목번호에 대해서 json으로 저장을 한다고 가정해봅시다.
{
  선택약관:[1,3,4],
  필수약관:[1,2,4] 
} 

이렇게 저장하기 보다는 약관 테이블을 따로 만들어서 약관 테이블에 환자seq, 약관seq를 매핑해서 저장하는 것이 좋지 않을까요?

만약 json으로 한다면 왜 json으로 하는 걸까요?

**Comment by hyun2371** [comment]
- 컬럼이 늘어나도 유연하게 변경할 수 있음
- 비정형 데이터 저장 용이
- 데이터를 조회하기만 하고 따로 가공이 필요없을 때
json으로 저장의 단점으로는 인덱싱, 검색에서 성능이 저하되고, 데이터 무결성을 확인할 수 없다고 하네요!

**Comment by hyun2371** [comment]
서연님) RDB 에서 json으로 저장을 하면 고유의 장점을 잃는 느낌이다.
RAG 파이썬 함수(vector search)->DB 정보만 적으면 embedding 문서
- 메타 데이터는 json으로 저장

*embedding 문서: 임베딩 대상이 될 문서
input 값으로 텍스트를 넣으면 알아서 저장

**Comment by hyun2371** [comment]
승현님) mongoDB에서 조회용도로만 쓰이는 데이터 json저장
