### ISSUE TITLE
[info][chapter08] mysql 공간 인덱스 관련 자료 공유합니다.

### ISSUE THREAD

**Issue by JisuPark-dev** [RealMysql-2407/study#11]
https://kong-dev.tistory.com/245
해당 블로그에 자세한 이야기가 있어서 공유드립니다.

혹시 프로젝트를 하시면서 공간 인덱스 사용경험이 있으시다면 댓글로 공유해주세요!

**Comment by sylee6529** [comment]
PostgreSQL에 PostGIS라는 Extension을 추가하여 공간데이터타입을 사용해 본 적이 있어서 찾아 봤는데, 여기는 GiST (Generalized Search Tree)라는 것을 사용해서 R-Tree와 유사하게 객체의 Bounding Box를 사용하여 인덱싱하고 트리구조를 통해 계층적으로 구성한다고 하더라구요

Polygon 까지 영역을 검색해보지는 않았지만, 현재 위치에서 5km 이내의 모든 레스토랑 찾기와 같은 조회는 함수를 사용하면 편하게 가져올 수 있었어요

https://luavis.me/server/how-to-deal-with-spatial-data
글을 좀 찾아봤는데, postgresql이 경우에 따라서 이 공간 index를 타는 것이 비효율적이라 판단되면 풀서치하는 방향으로 optimize하기 때문에, index 연산시 원치 않는 방향으로 계산하게 될 수도 있다고 하네요. 쿼리 보면서 이런 것도 파악해봐야 하는 구나 생각을 했습니다
