### ISSUE TITLE
[question][chapter08] 전문 검색 인덱스 vs 엘라스틱 서치

### ISSUE THREAD

**Issue by sylee6529** [RealMysql-2407/study#12]
찾아보면 Elastic Search을 사용하는게 성능이나 확장성 면에서 뛰어난 것 같은데, 저번에 Redis 사용을 논의한 것처럼 MySQL Full Text Search를 사용하는게 이점이 있는 경우가 있을까요?

**Comment by hyun2371** [comment]
지수님) 추가 인프라 관리 비용 절약
회사에서 MySQL로 로깅을 많이 함
elastic search로 로깅을 마이그레이션을 해야 하는데 번거로움

**Comment by hyun2371** [comment]
가현님) 구축 비용 들고, 지속적으로 유지보수해야 하는 것 같아서 리소스가 한정적인 프로젝트에서 쓰일 것 같다

**Comment by hyun2371** [comment]
지수님) DB가 2개 이상 (쓰기, 읽기), 분산 DB일 경우 elastic search에 통합한다면 유용할 듯

**Comment by hyun2371** [comment]
서연님) 엔드포인트가 많을 때 중계하는 인프라를 추가하는게 적절할 것 같다
*엔드포인트: 인프라, 컴퓨팅 리소스 맥락에서 말한 것; API, 컴퓨터 호스트로도 쓰이기도 함

**Comment by hyun2371** [comment]
승현님) 비용문제가 클 것 같아서 비용 절감 차원에서 쓸 것 같다. 
회사 측면이 아니라 개인 입장에서는 부담스러울 수 있다.
