### ISSUE TITLE
[question][chapter04] Thread Cache 최적화 방식

### ISSUE THREAD

**Issue by gitaepark97** [RealMysql-2407/study#14]
Thread Cache는 클라이언트 스레드를 재사용하기 위해 사용됩니다. Thread Cache의 크기는 thread_cache_size 변수로 설정 가능합니다.

- thread_cache_size가 너무 작은 경우: 스레드 생성과 파괴의 오버헤드 발생
- thread_cache_size가 너무 큰 경우: 불필요한 스레드 보관으로 인한 메모리 낭비

MySQL을 운영하는 상황에서 thread_cache_size를 어떤 기준으로 변경해야 성능을 최적화할 수 있을지 이야기 나눠보면 좋겠습니다.

**Comment by JisuPark-dev** [comment]
기태, 지수: 경험적으로 실험해보는 것 같다.

**Comment by JisuPark-dev** [comment]
승헌: 스레드 할당해주는 역할인데, 클라이언트 요청을 처리하기 위해서라면 스레드 사이즈가 최소 지점이 있을 것 같다. 

기태: 서비스 사용자가 많으면 커넥션이 많이 몰리고, 새벽시간에는 떨어지는 등이 될 수 있을 것 같다. peak타임을 버틸 수 있으면서도, 꽉 채우지는 않는 것을 보면 피크타입에 맞춰서 커넥션을 채우지는 않는 것 같다. 

지수: 그럼 피크타임에 성능 떨어지는 건 어떻게 대처할지 궁금해진다.

**Comment by JisuPark-dev** [comment]
기태: (-1로 한다면)os상황 맞춰서 스레드 생성하지 않을까. mysql 스레드는 os 스레드와 1:1 대응관계인 것으로 알고 있습니다.
