### ISSUE TITLE
[question][chapter04] 어댑티브 해시 인덱스 동적 조정 & 언두 로그 디스크 저장의 의의

### ISSUE THREAD

**Issue by gitaepark97** [RealMysql-2407/study#16]
어댑티브 해시 인덱스는 인덱스 크기를 동적으로 조정하는데, 조정 과정에 대해 제가 찾지 못해 같이 이야기 나눠보면 좋을 것 같습니다.

추가로 저는 언두 로그를 디스크에 저장하는 이유는 가상 메모리를 사용하는 이유와 동일하다고 생각이 되는데 다른 분들의 의견이 궁금합니다.

**Comment by JisuPark-dev** [comment]
1. 사용 비사용은 innodb_adaptive_hash_index로 가능한 것 같아요. `innodb_adaptive_hash_index = ON, OFF`
2. 런타임에서 활성화 비활성화:  `SET GLOBAL innodb_adaptive_hash_index = ON, OFF`
3. `innodb_adaptive_hash_index_parts`로 수동으로 파티션 갯수를 조정할 수도 있는 것 같습니다. 
4. `innodb_buffer_pool_size = 1G`를 조정해서 간접적으로 조정할 수는 있는 것 같아요!

**Comment by JisuPark-dev** [comment]
'저는 언두 로그를 디스크에 저장하는 이유는 가상 메모리를 사용하는 이유와 동일하다고 생각이 되는데 다른 분들의 의견이 궁금합니다.'이 부분은 이따가 좀 더 설명을 듣고 싶습니다!

**Comment by JisuPark-dev** [comment]
기태: 가상메모리도 메모리가 부족해서 디스크를 할당해서 사용하는 것인데, 언두로그를 디스크에 저장하는 의미도 같은 거라고 생각합니다.
지수: 프로그램 비정상 종료시 메모리가 다 날라가는 경우를 방지하기 위해서도 인 것 같아요.

**Comment by JisuPark-dev** [comment]
해시 인덱스 : 페이지 단위의 인덱스를 찾아가는 거라서, 로우 단위의 개념이 아니다. 거기서 b-tree로 로우를 찾아갑니다.

**Comment by JisuPark-dev** [comment]
해시 인덱스가 페이지 단위의 인덱스라서 범위 개념에서는 유용하지 않다.
