### ISSUE TITLE
[question][chapter04] 실무에서 실행계획을 어떻게 활용할 수 있을까요?

### ISSUE THREAD

**Issue by gitaepark97** [RealMysql-2407/study#18]
작성하는 모든 쿼리에 실행계획을 걸어보면 좋겠지만 실무에서는 시간이 부족합니다. 따라서 실행계획으로 걸어볼 쿼리들에 대한 기준이 있으면 좋을 것 같은데 다른 분들의 생각이 궁금합니다.

**Comment by JisuPark-dev** [comment]
1) 화면이 너무 늦게뜨면 
2) mysql에서는 슬로우쿼리에 대한 통계를 제공하는 걸로 알고 있습니다. 그래서 내가 몇초 이상을 슬로우쿼리라고 설정해서 나온 슬로우쿼리에 대해서 최적화를 해줄 수 있을 것 같습니다.

**Comment by JisuPark-dev** [comment]
개발중이라면 어떻게 해야할까? 또 orm에서 작성하는 모든 쿼리가 예상 불가능한데 어떻게 하나?
0. explain analyze - 내가 개발하는 모든 쿼리에 이거 해봐야해?
1. subquery최소화하자. 
2. left join 적게 하자. 
3. index가 타는지 확신이 안타는 쿼리에 대해서 돌릴려고 했다.
