### ISSUE TITLE
[question][chapter11] 대량 INSERT 시 고려사항

### ISSUE THREAD

**Issue by gitaepark97** [RealMysql-2407/study#21]
Load Data를 이용한 대량 INSERT 구문은 단일 스레드와 단일 트랜잭션으로 동작합니다.

삽입할 데이터가 리두 로그 혹은 언두 로그의 크기를 넘는다면 InnoDB의 메모리에서 디스크로 flush가 빈번하게 작동할 것으로 예상되어 삽입할 데이터의 크기는 로그들의 크기보다 작게 분배하는 것이 좋을 것 같습니다.
추가로 삽입할 데이터를 나누어서 여러 INSERT 구문으로 실행시킨다면 멀티 스레드의 장점도 가져갈 수 있을 것 같습니다.

이외의 고려사항에 대해 어떻게 생각하시는지 궁금합니다.

**Comment by JisuPark-dev** [comment]
innodb 버퍼풀의 크기도 커야할 것 같습니다.
유니크 인덱스와 외래키 제약사항도 설정을 꺼놓으면 해당 검증을 피할 수 있어서 속도가 올라갈 것 같습니다. 

그리고 insert하는 데이터의 순서가 보장되어야 한다면, 멀티스레드를 사용하지 못할 것 같습니다.

**Comment by JisuPark-dev** [comment]
기태: 엑셀에 id를 만들고 auto increment를 끄고, 나중에 키면 됩니다.
