### ISSUE TITLE
[question][chapter11]inner join, outer join을 구분해서 쿼리 작성을 하시나요?

### ISSUE THREAD

**Issue by JisuPark-dev** [RealMysql-2407/study#22]
이번에 공부하면서 inner join은 둘다 있어야지만 데이터가 반환되고, 
outer join은 드라이빙하는 테이블은 모두 결과로 반환하고 드리아븐되는 칼럼 정보는 만약 없으면 null로 처리되대 데이터자체는 반환된다는 것을 알게 되었습니다.

실무에서는 무조건 left join만 무지성으로 사용해오고 있었는데요, 책에서 보니깐 가급적으로 inner join을 사용할 수 있으면 옵티마이저의 최적화를 위해서 inner join을 사용하라고 하더군요...! 

그간 어떻게 사용해오셨는지 궁금합니다.

ps) 아우터조인을 살리고 싶다면 where이 아닌 on 조건을 사용하라는 가르침도 받았습니다...!

**Comment by gitaepark97** [comment]
저도 left join을 주로 사용하고, full outer join이 필요한 경우에만 left join, right join union해서 사용했었는데요. inner join로 해결이 가능한가가 쿼리 작성 시 고려사항에 우선순위가 높아서 제가 아는 선에서는 inner join으로 가능한데 outer join을 사용한 경우는 없었던 것 같습니다.
