### ISSUE TITLE
[question][chaptor05] 네임드락을 사용해야하는 경우는 언제일까요? 사용하면 어떻게 되는 것일까요?

### ISSUE THREAD

**Issue by JisuPark-dev** [RealMysql-2407/study#3]
책에서는 `String`에 대해서 락을 건다고 했습니다.
복잡한 요건으로 레코드 변경하는 트랜잭션에 유용할 수 있다. 배치는 한번에 여러 쿼리 실행하면서 데드락의 원인이 되곤 한다.
이 때, 동일 데이터를 변경하거나 참조하는 프로그램끼리 분류해서 네임드락을 걸고 쿼리를 실행하면 간단하게 해결 가능하다.
라고 합니다.

예를 들어서 주문 처리 시스템에서 네임드 락 사용 예시를 들어보겠습니다.

하나의 상품에 대한 주문이 많이 들어오는 상황에서 특정 상품의 재고를 순차적으로 조정해야합니다.

이를 위해서 product id가 123이라면 `SELECT GET_LOCK('product_123', 10);`을 통해서 product_123이라는 이름의 락을 10초 동안 시도합니다. 만약 획득했다면 1을 반환하고 획득하지 못했다면 0을 반환합니다.

만약 락을 획득했다면 
```
START TRANSACTION;

UPDATE products 
SET stock = stock - 1 
WHERE product_id = 123;

COMMIT;
```
을 통해서 재고 수정 작업을 수행해줍니다.

이후 락을 해제해줍니다.
`SELECT RELEASE_LOCK('product_123');`

**Comment by JisuPark-dev** [comment]
근데 이렇게 매번 update할 때마다 lock을 얻어서 업데이트하면 락 획득 및 해제의 오버해드가 커져서 성능상 늦어지지 않을까 궁금하네요

**Comment by hyun2371** [comment]
말씀하신 것처럼 여러 프로세스나 스레드에서 재고 감소 로직을 처리할 때 쓰인다고 하네요. 

[블로그](https://0soo.tistory.com/255)에서 장점을 찾아보았습니다!
MySQL에서 제공하는 락이기 때문에 ZooKeeper, Redis 같은 외부 인프라를 구축할 필요가 없습니다.
사용자가 지정한 문자열에 대해서만 락을 걸기 때문에 특정 테이블이나 레코드에 대한 접근이 제한되지 않습니다.

**Comment by JisuPark-dev** [comment]
네임드락이 있는데도 Redis를 쓰는 이유는 ?  -> mysql을 쓰는 이유는 더 인프라를 추가하지 않으면서 할 수 있어서임. 책임을 위임할 수 있다는 측면에서는 Redis를 쓰는 것이 더 좋아보이기도 한다. 

redisson이 Redis 라이브러리인데 업데이트가 잘 안되서, 관리측면에서 어렵다. 

mysql 버전과 호환되지 않아서 오류가 터질 수 있을까?

**Comment by JisuPark-dev** [comment]
회사에서 동료랑 네임드락과 redis의 사용처에 대해서 이야기 해봤습니다.
만약 db가 한개 이상이라면 네임드락이 각 db간에 공유가 되지 않으므로 redis를 사용하는게 맞다고 결론 내렸습니다!
