### ISSUE TITLE
[question][chapter05] 자동증가락이 사용되지 않는다면 어떻게 겹치지 않을까요?

### ISSUE THREAD

**Issue by JisuPark-dev** [RealMysql-2407/study#5]
MYSQL 5.1버전 이상에서는 INSET 할 때, 정확한 갯수를 알면 자동증가락을 걸지 않고 뮤텍스로 처리한다고 했는데, 
현실적으로 정확한 갯수를 알수 없는 것 아닌가요? 뮤텍스로 처리한다는 것은 무슨 뜻일까요?

**Comment by sonshn** [comment]
일반적인 INSERT와 대량의 데이터를 한 번에 저장하는 Bulk INSERT를 구분해서 설명하려고 했던 것 같습니다!

답변 내용과 직접적인 관련은 없지만 [흥미로운 글](https://velog.io/@ttomy/batch-insert)이 있어 공유합니다.

**Comment by JisuPark-dev** [comment]
배치를 돌리다던지 하면 정확한 갯수를 알 수 있을 것 같다.
