### ISSUE TITLE
[question][info] 네임드 락 vs 트랜잭션의 차이

### ISSUE THREAD

**Issue by sylee6529** [RealMysql-2407/study#6]
네임드 락은 지정한 문자열을 identifier로 하여 Lock을 얻고, 락을 얻은 동안 여러 작업을 한꺼번에 실행하는 것이라고 이해했습니다.
그리고 네임드 락 그리고 트랜잭션은 동시성 제어를 위해 사용됩니다.

Rollback 지원 기능 외에 이 2가지가 다른 것 같긴한데, 헷갈리는 부분이 많아 명확하게 정리하고 싶다는 생각이 들었습니다.

1. 격리수준
트랜잭션은 DB에서 제공하는 다양한 격리수준을 사용할 수 있지만, 네임드락은 단순히 정의하는 특정 리소스에 대한 접근을 제어합니다.

2. 지속 시간
트랜잭션은 (목적에 맞게 사용한다면) 일반적으로 짧은 시간 유지되지만, 네임드 락은 필요에 따라 장시간 유지됩니다.

3. 관리
트랜잭션은 개발자가 시작, 커밋, 롤백 시점을 지정, 관리해야 한다면 네임드 락은 락의 획득, 해제 시점을 관리합니다.

정리해보니 헷갈렸던 이유는, 네임드락은 작업에 대한 동기화를 걺으로써 실제 데이터베이스 객체에 대한 동기화를 지원하는 것을 이해하지 못해 어려웠던 것 같습니다.

그리고 작업에 대한 동기화라는 것이, 모든 세션에서 같은 이름의 락을 공유한다는 특징을 알면 차이가 더 또렷하게 느껴지는 것 같습니다. 그래서 다른 세션에서도 동일한 이름의 작업을 하지 않기 때문에 중복 작업 방지라는 것이 실행 예시로 있는 듯합니다.

제가 이해하는게 맞는지, 혹은 생각나는 차이점이 더 있다면 의견 나누어 보면 좋을 것 같습니다! 👍

**Comment by JisuPark-dev** [comment]
네임드 락은 특정 리소스나 작업에 대해 동시성을 제어하기 위해 사용됩니다. 데이터베이스 테이블이나 레코드와 직접적으로 연관되지 않고, 필요한 임의의 리소스에 대해 사용할 수 있습니다.

트랜잭션은 데이터베이스 객체(테이블, 레코드)에 대한 변경 사항을 다룹니다. 데이터베이스의 데이터를 일관되게 유지하는 것이 목적이기 때문에, 트랜잭션은 데이터베이스 레벨에서 락을 관리합니다.
