### ISSUE TITLE
[question][chapter08]DBMS에서 순차IO보다 랜덤 IO가 더 많은 이유는?

### ISSUE THREAD

**Issue by JisuPark-dev** [RealMysql-2407/study#8]

**Comment by hyun2371** [comment]
순차 I/O
- 테이블의 전체 데이터 조회
- 풀 테이블 스캔

랜덤 I/O
- WHERE 절이 포함된 쿼리 실행해 조회, 삭제, 수정
- 인덱스 레인지 스캔

대부분 사용자가 특정 조건에 맞는 데이터를 요청해 DBMS가 처리하기 때문인듯합니다.

**Comment by JisuPark-dev** [comment]
일반적으로 풀 테이블 스캔은 순차 I/O를 사용하므로, 랜덤 I/O는 발생하지 않습니다. 그러나 특정 상황에서는 랜덤 I/O가 발생할 수 있습니다:

1.	테이블이 파편화된 경우: 테이블이 디스크 상에서 여러 조각으로 나뉘어 있는 경우, 풀 테이블 스캔이 랜덤 I/O를 발생시킬 수 있습니다. 이는 데이터가 디스크의 여러 위치에 분산되어 있어 연속적으로 읽을 수 없을 때 발생합니다.
2.	데이터 블록 캐싱: 데이터베이스가 메모리 내에서 데이터를 캐싱하고 있다면, 물리적으로 디스크에서 읽는 것보다, 메모리에서 랜덤하게 데이터를 읽는 상황이 발생할 수 있습니다. 이 경우, 메모리에서의 랜덤 I/O와 유사한 상황이 발생할 수 있습니다.
3.	병렬 처리: 일부 데이터베이스 시스템에서는 풀 테이블 스캔을 병렬로 처리하기 위해 여러 I/O 요청을 동시에 발생시킬 수 있으며, 이 경우 I/O 패턴이 랜덤하게 보일 수 있습니다.

**Comment by JisuPark-dev** [comment]
랜덤 io를 순차 io로 바꾸는 것은 거의 없고, 랜덤 io의 숫자를 줄이는 것이 db 튜닝의 목적이다.

**Comment by hyun2371** [comment]
쿼리를 튜닝한다고 랜덤 I/O가 순차 I/O로 변하는 상황은 많지 않다고 한다. 즉, 쿼리 튜닝의 목적은 랜덤 I/O를 줄이는 것이다. 즉, 꼭 필요한 데이터만 읽도록 쿼리를 개선하는 것이 중요하다.
인덱스 레인지 스캔은 데이터를 읽기 위해 주로 랜덤 I/O를 사용하고, 풀 테이블 스캔은 순차 I/O를 사용한다. 따라서 큰 테이블의 레코드를 읽는 작업을 할 때 옵티마이저가 인덱스 대신 풀 테이블 스캔을 하도록 유도하는 경우도 있다고 한다.

출처: https://sothoughtful.dev/posts/about-index/
