### ISSUE TITLE
[info][chaptor08] 프로젝트에서 언제 인덱스를 사용해야 할까?

### ISSUE THREAD

**Issue by hyun2371** [RealMysql-2407/study#9]
- 데이터 범위가 크거나 규모가 큰 테이블
- 데이터 중복이 적음
- 데이터 수정, 삭제보다 조회 빈도가 많을 때
- 정렬로 이점을 볼 수 있을 때
- JOIN, WHERE, ORDER BY를 자주 호출하는 컬럼

**Comment by sonshn** [comment]
@JisuPark-dev 
- 인덱스 자체는 모든 테이블에 사용
- 어디에 어떤 인덱스를 사용할 지를 고민하는 것 같아요 😄 
- API 요청 시간을 로깅하고, 1초 이상이 소요되면 Slow Query 알림이 뜨도록 함 (Elastic Search와 Slack 푸시 알림 API 이용)
- 10개 정도의 인덱스만 사용해도 시간이 오래 걸린다! 많다고 좋은 것이 아니다...

**Elastic Search**
- 로깅을 위한 툴인가요? 네!
- 3가지가 합쳐짐: 로깅 + 그래프 이미지(분석) + 검색(로깅을 검색)
- 비용? 무료 버전 사용중 😄 유료 버전의 경우 Slack과 바로 연동이 가능하지만, 무료 버전은 직접...
- 작업환경(dev, prod 등등)에 따른 서버도 각각 있지만, 로그 관리 서버도 따로 있습니다! Elastic Search용도로

**Comment by hyun2371** [comment]
[elastic search란?](https://sihyung92.oopy.io/database/elasticsearch/1)
